// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQQtz6irFLvF0wQhtpgfGqiU52N-eEl8',
    appId: '1:225763115404:web:f925cb8a9a6dab2f0716a9',
    messagingSenderId: '225763115404',
    projectId: 'radiantglow-56323',
    authDomain: 'radiantglow-56323.firebaseapp.com',
    storageBucket: 'radiantglow-56323.appspot.com',
    measurementId: 'G-G8FQP0F3HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmDup6GzMCkCxZ5kszU6C-FWtwmczCa20',
    appId: '1:225763115404:android:c07e7e5dc639bfe30716a9',
    messagingSenderId: '225763115404',
    projectId: 'radiantglow-56323',
    storageBucket: 'radiantglow-56323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWiPzE30CVJ1BPF1p1x3QVSIGuX9hR2x0',
    appId: '1:225763115404:ios:37db970ba8a8b1b40716a9',
    messagingSenderId: '225763115404',
    projectId: 'radiantglow-56323',
    storageBucket: 'radiantglow-56323.appspot.com',
    iosBundleId: 'com.example.radiantglow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWiPzE30CVJ1BPF1p1x3QVSIGuX9hR2x0',
    appId: '1:225763115404:ios:37db970ba8a8b1b40716a9',
    messagingSenderId: '225763115404',
    projectId: 'radiantglow-56323',
    storageBucket: 'radiantglow-56323.appspot.com',
    iosBundleId: 'com.example.radiantglow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcQQtz6irFLvF0wQhtpgfGqiU52N-eEl8',
    appId: '1:225763115404:web:20c3e85daeaf5db40716a9',
    messagingSenderId: '225763115404',
    projectId: 'radiantglow-56323',
    authDomain: 'radiantglow-56323.firebaseapp.com',
    storageBucket: 'radiantglow-56323.appspot.com',
    measurementId: 'G-B3C5TQG5J1',
  );
}
